services:
  postgres:
    image: postgres:16
    container_name: space_etl_db
    environment:
      POSTGRES_USER: space_user
      POSTGRES_PASSWORD: space_pass
      POSTGRES_DB: space_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: